# Generated by Django 3.1.1 on 2021-02-11 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210211_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Media', 'Media'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('Repair', 'Repair'), ('Cleaning', 'Cleaning'), ('Book', 'Book'), ('Household', 'Household'), ('Fashion', 'Fashion')], max_length=20),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='auctions.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
