# Generated by Django 3.1.1 on 2021-02-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210211_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Auction'),
        ),
    ]
